### ISSUE TITLE
mnist vs python-mnist

### ISSUE THREAD

**Issue by graingert** [datapythonista/mnist#6]
@datapythonista
@sorki

there's https://pypi.python.org/pypi/mnist/ and https://pypi.python.org/pypi/python-mnist/

Seems like a bit of duplication of effort? How about merging the projects?

**Comment by graingert** [comment]
https://github.com/sorki/python-mnist/issues/16

**Comment by datapythonista** [comment]
I don't really have the time now for taking a look at merging the projects. When I implemented it, it wasn't any other project that was doing what I wanted, that's why I created it. Not sure what could be merged, I see that python-mnist has much more code than this, some randomization which I'm not quite sure what it's for...

I'm happy with this project the way it is, the simplest way to download and parse the mnist dataset. I'm happy to accept PRs, but I don't see how to merge both projects, even if conceptually I agree, that we should try to avoid duplicating the effort.
